// Global messages
export const ADD_GLOBAL_MESSAGE = 'ADD_GLOBAL_MESSAGE';
export const REMOVE_GLOBAL_MESSAGE = 'REMOVE_GLOBAL_MESSAGE';

// Login
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN = 'LOGIN';

// Signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_COMPLETED = 'SIGNUP_COMPLETED';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// GET COLLECTIONS
// Approved apps
export const APPROVED_APPS_REQUEST = 'APPROVED_APPS_REQUEST';
export const APPROVED_APPS_SUCCESS = 'APPROVED_APPS_SUCCESS';
export const APPROVED_APPS_FAILURE = 'APPROVED_APPS_FAILURE';

// PUT COLLECTION ITEMS
export const PUT_APP_COLLECTION_ITEM_REQUEST = 'PUT_APP_COLLECTION_ITEM_REQUEST';
export const PUT_APP_COLLECTION_ITEM_SUCCESS = 'PUT_APP_COLLECTION_ITEM_SUCCESS';
export const PUT_APP_COLLECTION_ITEM_FAILURE = 'PUT_APP_COLLECTION_ITEM_FAILURE';

// GET ENTITIES
// Apps
export const APP_REQUEST = 'APP_REQUEST';
export const APP_SUCCESS = 'APP_SUCCESS';
export const APP_FAILURE = 'APP_FAILURE';
// Apps Extended
export const APP_EXTENDED_REQUEST = 'APP_EXTENDED_REQUEST';
export const APP_EXTENDED_SUCCESS = 'APP_EXTENDED_SUCCESS';
export const APP_EXTENDED_FAILURE = 'APP_EXTENDED_FAILURE';
// Thumbs
export const THUMB_REQUEST = 'THUMB_REQUEST';
export const THUMB_SUCCESS = 'THUMB_SUCCESS';
export const THUMB_FAILURE = 'THUMB_FAILURE';